### PR TITLE
Adds `Offerings.getCurrentOfferingForPlacement()`

### PR DESCRIPTION
**Pull request by JayShortway**
This adds the `Offerings.getCurrentOfferingForPlacement()` functionality back, which was removed in https://github.com/RevenueCat/purchases-kmp/pull/121. 

In order to make this non-breaking, I added a lambda constructor parameter to `Offerings`. I don't entirely love it, but all the alternatives I could think of are breaking in one way or another (e.g. making `Offerings` an interface). Please do let me know all your ideas! I'm also happy to discuss this more. 

- Dependency: https://github.com/RevenueCat/purchases-hybrid-common/pull/938
- Addresses: https://github.com/RevenueCat/purchases-kmp/issues/242

### CODE REVIEW

**Review by tonidero — COMMENTED** [review]
Hmm the alternative is following the API in RN, where this method is in `Purchases`: https://github.com/RevenueCat/react-native-purchases/blob/a34e4ab926254c58c3f53c8a8ea6aced133b5684/src/purchases.ts#L407.... Not sure if I prefer that TBH, to avoid passing the block... Wdyt? Also running out of other ideas without making it a breaking change

**Comment by JayShortway** [comment]
@tonidero Hmm yea I don't think I prefer that either. That's an(other) async API which I think is less ergonomic than just making it available on the `Offerings` type. 

Maybe adding the lambda to the constructor is not super terrible? Devs are unlikely to be constructing it, and even if they are (e.g. in tests), they don't have to come up with an implementation of the lambda as it's optional. 

There's always the option to deprecate the constructor and make it an interface in a major, but then we have an interface, which is not great in itself haha.

**Comment by tonidero** [comment]
Hmm so after looking at the other hybrids, I think all of them are actually using the function in `Purchases`... So I'm thinking, for the sake of consistency, I might prefer that.

FWIW, I think usage would be fine, as in the developer can just call the `Purchases.sharedInstance.getCurrentOfferingForPlacement` wherever they need, since the value should be cached in the native layer, it should be quick...

**Comment by JayShortway** [comment]
@tonidero I think we're either going to be consistent with the native platform SDKs or with the hybrid SDKs. 

I agree that it'll be quick because it's cached, but it is still an async API. Async APIs are far less user-friendly than sync APIs imo. What if a dev wants to get all `Offering`s _and_ get the current one for a placement? 
- In the `Purchases.sharedInstance.getCurrentOfferingForPlacement` case, they'd need to call 2 async APIs (`Purchases.sharedInstance.getCurrentOfferingForPlacement` and `Purchases.sharedInstance.getOfferings`). If they're not using coroutines, they are officially in callback hell. 
- In the `Offerings.getCurrentOfferingForPlacement` case, they'd just need the one call to `Purchases.sharedInstance.getOfferings` and have all they need. 

I think having a slightly odd constructor parameter (that devs are unlikely to call) is a price worth paying for this user-friendliness. 

@vegaro Wanna be the tie breaker here? 😄

**Comment by vegaro** [comment]
I am leaning towards the native way of doing this (`Offerings.getCurrentOfferingForPlacement`). Even if we have to store that lambda in the constructor, I think that's implementation details for a nicer API.

**Review by vegaro — APPROVED** [review]

**Comment by tonidero** [comment]
Sounds good then 👍

**Pull request merged**
