### PR TITLE
Greatly simplifies how Price.amountMicros is determined on iOS.

### PR DESCRIPTION
**Pull request by JayShortway**
Since PHC did not expose the actual price amount on iOS, we were reconstructing it by parsing the formatted price string. Besides being very brittle, this might also be the cause of https://github.com/RevenueCat/purchases-kmp/issues/161, as we return `0` if the price formatter is null. The meat of this PR is in `Price.ios.kt`. 

**Note**: this is ready for review. It's just dependent on a few external factors:

## Blockers
- [x] https://github.com/RevenueCat/purchases-hybrid-common/pull/911
- [x] A PHC release with ☝️ 
- [x] Updating this PR with the new PHC version number.

### CODE REVIEW

**Review by tonidero — COMMENTED** [review]
Changes LGTM! Will give it the stamp once it's ready for review :)

**Comment by tonidero** [comment]
I just merged the PHC bump in #174, so we should rebase this PR @JayShortway

**Comment by JayShortway** [comment]
@tonidero Thanks, done!

**Review by tonidero — APPROVED** [review]
LGTM!

**Pull request merged**
